### ISSUE TITLE
Cross-page link syntax?

### ISSUE THREAD

**Issue by SeaDude** [mrvautin/squido-docs#2]
Hello,

To link to different pages within a Squido site, would we use the rendered URL or is there a way to use relative links in markdown?

**Example:**
- Use `[Link here](https://site.com/wheres-the-link/)` OR IS THERE A WAY TO
- Use `[Link here](./wheres-the-link.markdown)`

**Comment by mrvautin** [comment]
You should be able to use `[Link here](/wheres-the-link.markdown)`.
